# ---------------- #
#   Main Configs   #
# ---------------- #
#baseurl: https://jasperbalcony.github.io/
url: https://jasperbalcony.github.io/
date_format: "ordinal"
title: Jasper
subtitle: "Jasper"
description: "Jasper"
keywords: jaser, xgwang
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: JasperXgwang
organization: Meizu, Inc.
organization_url: https://www.meizu.com
location: zhuhai, China
email: jasperxgwang@126.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
paginate_path: "/blog/page:num/"
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: JasperBalcony/JasperBalcony.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: JasperXgwang
douban_username: JasperXgwang
facebook_username: JasperXgwang
weibo_username: JasperXgwang
zhihu_username: JasperXgwang
twitter_username: JasperXgwang

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: JasperXgwang
disqus_username: JasperXgwang
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-92285152-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, Design Patterns]
skill_mobile_app_keywords: [J2EE Engineering]
skill_windows_keywords: [Java]
